[[repos]]
repo = "builtin"
hooks = [
  { id = "check-added-large-files" },
  { id = "check-case-conflict" },
  { id = "check-illegal-windows-names" },
  { id = "end-of-file-fixer" },
  { id = "trailing-whitespace" },
]

[[repos]]
repo = "https://github.com/editorconfig-checker/editorconfig-checker"
rev = "v3.11.1"
hooks = [
  {
    id = "editorconfig-checker",
    # Exclude c++ files because clang-format alignment rules are incompatible
    # with editorconfig.
    args = ["-exclude", "\\.cpp$|\\.hpp$"],
  }
]

[[repos]]
repo = "https://github.com/igorshubovych/markdownlint-cli"
rev = "v0.49.1"
hooks = [{ id = "markdownlint" }]

[[repos]]
repo = "https://github.com/pocc/pre-commit-hooks"
rev = "v1.3.5"
hooks = [
  { id = "clang-format" },
  {
    id = "clang-tidy",
    # -quiet is necessary to prevent hook failure.
    args = ["-p=build", "-quiet"],
  },
]

[[repos]]
repo = "https://github.com/tombi-toml/tombi-pre-commit"
rev = "v1.4.1"
hooks = [{ id = "tombi-format" }, { id = "tombi-lint" }]

[[repos]]
repo = "https://github.com/google/yamlfmt"
rev = "v0.21.0"
hooks = [{ id = "yamlfmt" }]
